//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandProfile
    {
        public BrandProfile()
        {
            this.Webinars = new HashSet<Webinar>();
            this.StudentBlogs = new HashSet<StudentBlog>();
            this.BrandBannerImages = new HashSet<BrandBannerImage>();
        }
    
        public long BrandID { get; set; }
        public string BrandName { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public string ContactNo { get; set; }
        public long BrandLogoID { get; set; }
        public string BrandLink { get; set; }
        public string YoutubeURL { get; set; }
        public string BrandContent { get; set; }
    
        public virtual ProfilePic ProfilePic { get; set; }
        public virtual ICollection<Webinar> Webinars { get; set; }
        public virtual ICollection<StudentBlog> StudentBlogs { get; set; }
        public virtual ICollection<BrandBannerImage> BrandBannerImages { get; set; }
    }
}
