//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampusExpertRequest
    {
        public long RequestID { get; set; }
        public string RequestMessage { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public long CampusID { get; set; }
        public long RequestedToID { get; set; }
        public System.DateTime RequestedOn { get; set; }
        public Nullable<bool> IsAdminApproved { get; set; }
        public Nullable<bool> IsExpertApproved { get; set; }
    
        public virtual CampusProfile CampusProfile { get; set; }
        public virtual ExpertProfile ExpertProfile { get; set; }
    }
}
