//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        public long EmailTemplateID { get; set; }
        public string EmailTemplate1 { get; set; }
        public string EmailSubject { get; set; }
    }
}
