//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertProfile
    {
        public ExpertProfile()
        {
            this.CampusExpertRequests = new HashSet<CampusExpertRequest>();
            this.ExpertTagMappings = new HashSet<ExpertTagMapping>();
            this.Messages = new HashSet<Message>();
            this.RecommandAFriends = new HashSet<RecommandAFriend>();
            this.Webinars = new HashSet<Webinar>();
        }
    
        public long ExpertID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public string LoginID { get; set; }
        public System.DateTime RegisteredOn { get; set; }
        public string ContactNo { get; set; }
        public string AboutMe { get; set; }
        public string Company { get; set; }
        public string Position { get; set; }
        public Nullable<int> ExperienceYear { get; set; }
        public Nullable<int> ExperienceMonth { get; set; }
        public string LinkedInProfileLink { get; set; }
        public string TweeterProfileLink { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<long> ProfilePicID { get; set; }
        public bool IsConfirmed { get; set; }
        public decimal ProfileCompleted { get; set; }
        public bool IsEliteMaster { get; set; }
    
        public virtual ICollection<CampusExpertRequest> CampusExpertRequests { get; set; }
        public virtual ProfilePic ProfilePic { get; set; }
        public virtual ICollection<ExpertTagMapping> ExpertTagMappings { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<RecommandAFriend> RecommandAFriends { get; set; }
        public virtual ICollection<Webinar> Webinars { get; set; }
    }
}
