//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertTagMapping
    {
        public long ExpertTagMappingID { get; set; }
        public long TagID { get; set; }
        public long ExpertID { get; set; }
    
        public virtual TagMaster TagMaster { get; set; }
        public virtual ExpertProfile ExpertProfile { get; set; }
    }
}
