//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilePic
    {
        public ProfilePic()
        {
            this.Webinars = new HashSet<Webinar>();
            this.CampusProfiles = new HashSet<CampusProfile>();
            this.ExpertProfiles = new HashSet<ExpertProfile>();
            this.StudentProfiles = new HashSet<StudentProfile>();
            this.BrandProfiles = new HashSet<BrandProfile>();
        }
    
        public long ProfilePicID { get; set; }
        public string ProfilePicPath { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual ICollection<Webinar> Webinars { get; set; }
        public virtual ICollection<CampusProfile> CampusProfiles { get; set; }
        public virtual ICollection<ExpertProfile> ExpertProfiles { get; set; }
        public virtual ICollection<StudentProfile> StudentProfiles { get; set; }
        public virtual ICollection<BrandProfile> BrandProfiles { get; set; }
    }
}
