//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusMaster
    {
        public StatusMaster()
        {
            this.Webinars = new HashSet<Webinar>();
        }
    
        public long statusID { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<Webinar> Webinars { get; set; }
    }
}
