//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProfile
    {
        public StudentProfile()
        {
            this.StudentBlogs = new HashSet<StudentBlog>();
        }
    
        public long StudentID { get; set; }
        public string StudentName { get; set; }
        public string EmailID { get; set; }
        public string LoginID { get; set; }
        public string Password { get; set; }
        public string CampusName { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<long> Year { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<long> ProfilePicID { get; set; }
        public System.DateTime RegisteredOn { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
    
        public virtual ProfilePic ProfilePic { get; set; }
        public virtual ICollection<StudentBlog> StudentBlogs { get; set; }
    }
}
