//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentBlog
    {
        public int StudentBlogID { get; set; }
        public string Blog { get; set; }
        public string BlogTitle { get; set; }
        public long StudentID { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime UpdationDate { get; set; }
        public Nullable<long> BrandID { get; set; }
    
        public virtual StudentProfile StudentProfile { get; set; }
        public virtual BrandProfile BrandProfile { get; set; }
    }
}
