//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagMaster
    {
        public TagMaster()
        {
            this.ExpertTagMappings = new HashSet<ExpertTagMapping>();
            this.WebinarTagMappings = new HashSet<WebinarTagMapping>();
        }
    
        public long TagID { get; set; }
        public string TagName { get; set; }
    
        public virtual ICollection<ExpertTagMapping> ExpertTagMappings { get; set; }
        public virtual ICollection<WebinarTagMapping> WebinarTagMappings { get; set; }
    }
}
