//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebinarAnswer
    {
        public long AnswerID { get; set; }
        public Nullable<long> QuestionID { get; set; }
        public string Answer { get; set; }
        public bool IsCorrect { get; set; }
    
        public virtual WebinarQuestion WebinarQuestion { get; set; }
    }
}
