//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebinarFeedBack
    {
        public long FeedbackID { get; set; }
        public string FeedBack { get; set; }
        public long CampusWabinarID { get; set; }
        public System.DateTime SubmittedOn { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual CampusWebinarMapping CampusWebinarMapping { get; set; }
    }
}
