//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebinarTagMapping
    {
        public long WebinarTagMappingID { get; set; }
        public long WebinarID { get; set; }
        public long TagID { get; set; }
    
        public virtual TagMaster TagMaster { get; set; }
        public virtual Webinar Webinar { get; set; }
    }
}
