//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Webinar
    {
        public Webinar()
        {
            this.WebinarQuestions = new HashSet<WebinarQuestion>();
            this.WebinarTagMappings = new HashSet<WebinarTagMapping>();
            this.CampusWebinarMappings = new HashSet<CampusWebinarMapping>();
        }
    
        public long WebinarID { get; set; }
        public string WebinarName { get; set; }
        public string WebinarSummary { get; set; }
        public string WebinarDescription { get; set; }
        public string WhatWillYouLearn { get; set; }
        public System.DateTime FromDateTime { get; set; }
        public System.TimeSpan TimeDuration { get; set; }
        public Nullable<System.DateTime> ToDateTime { get; set; }
        public long statusID { get; set; }
        public string YoutubeUrl { get; set; }
        public long WebinarPicID { get; set; }
        public Nullable<long> BrandID { get; set; }
        public Nullable<long> ExpertID { get; set; }
    
        public virtual BrandProfile BrandProfile { get; set; }
        public virtual ExpertProfile ExpertProfile { get; set; }
        public virtual ProfilePic ProfilePic { get; set; }
        public virtual StatusMaster StatusMaster { get; set; }
        public virtual ICollection<WebinarQuestion> WebinarQuestions { get; set; }
        public virtual ICollection<WebinarTagMapping> WebinarTagMappings { get; set; }
        public virtual ICollection<CampusWebinarMapping> CampusWebinarMappings { get; set; }
    }
}
