//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebinarQuestion
    {
        public WebinarQuestion()
        {
            this.WebinarAnswers = new HashSet<WebinarAnswer>();
        }
    
        public long QuestionID { get; set; }
        public Nullable<long> WebinarID { get; set; }
        public string Question { get; set; }
    
        public virtual Webinar Webinar { get; set; }
        public virtual ICollection<WebinarAnswer> WebinarAnswers { get; set; }
    }
}
